In [1]:
import torch
from torch import nn
import keras
import numpy as np

/home/radonc/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [13]:
import keras.backend as K

In [21]:
a = np.array( range(8))
a = a.reshape((2,2,2)).astype('float')

In [22]:
b = np.array( range(8,0,-1))
b = b.reshape( (2,2,2)).astype(float)

In [23]:
inp = torch.from_numpy(a)
tar = torch.from_numpy(b)

In [24]:
loss = nn.MSELoss()

In [25]:
val = loss(inp, tar)

In [26]:
val

tensor(22., dtype=torch.float64)

In [27]:
inp

tensor([[[0., 1.],
         [2., 3.]],

        [[4., 5.],
         [6., 7.]]], dtype=torch.float64)

In [28]:
tar

tensor([[[8., 7.],
         [6., 5.]],

        [[4., 3.],
         [2., 1.]]], dtype=torch.float64)

In [29]:
print np.mean( np.square(a - b))

22.0


In [30]:
inpK = K.variable(a)
tarK = K.variable(b)

In [16]:
inpK

<tf.Variable 'Variable_1:0' shape=(2, 2, 2) dtype=float32_ref>

In [31]:
K.loss.mse(inpK, tark)

AttributeError: 'module' object has no attribute 'loss'

In [33]:
valK   = keras.losses.mean_squared_error( inpK, tarK)

In [37]:
K.eval(valK)

array([[50., 10.],
       [ 2., 26.]], dtype=float32)

In [36]:
K.eval(valK)

array([[50., 10.],
       [ 2., 26.]], dtype=float32)

In [38]:
print np.mean( np.square(a - b), axis=-1)

[[50. 10.]
 [ 2. 26.]]


In [40]:
a = np.zeros( (4,5,6))
b = np.ones( (2,2,2))

In [72]:
z = [0  ,2]
s1 = np.array( x)
s2 = np.expand_dims( s1, axis =1)
s = np.expand_dims(s2, axis = 2)

In [73]:
print s
print s.shape

[[[0]]

 [[2]]]
(2, 1, 1)


In [94]:
z = [0 ,2 ]
s2 = np.array(z)
s = np.reshape( s2, (1,2,1))

In [95]:
print s
print s.shape

[[[0]
  [2]]]
(1, 2, 1)


In [88]:
y = [ 1 , 2]
r = np.array( y)
r = np.expand_dims(r, axis = 1)
r = np.expand_dims( r, axis = 0)

In [89]:
print r
print r.shape

[[[1]
  [2]]]
(1, 2, 1)


In [86]:
x = [0 ,1 ]
c = np.array( x)
c = np.expand_dims( c, axis=0)
c = np.expand_dims( c, axis = 0)

In [87]:
print c
print c.shape

[[[0 1]]]
(1, 1, 2)


In [90]:
a[s, r, c] = b

In [91]:
a

array([[[0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])